labgrid-blocktrron-hpe_msm460:
  location: blocktrron-closet
  RawSerialPort:
    port: "/dev/serial/by-id/usb-FTDI_FT232R_USB_UART_ABSCG1ZV-if00-port0"
    speed: 115200
  NetworkPowerPort:
    model: ubus
    host: "http://192.168.128.2/ubus"
    index: 3
  TFTPProvider:
    internal: "/srv/tftp/hpe_msm460/"
    external: "hpe_msm460/"
    external_ip: "192.168.103.1"
  NetworkService:
    address: "192.168.1.1%vlan103"
    username: "root"

labgrid-blocktrron-tplink_tl-wr842n-v3:
  location: blocktrron-closet
  RawSerialPort:
    port: "/dev/serial/by-id/usb-Silicon_Labs_CP2104_USB_to_UART_Bridge_Controller_027IJXPW-if00-port0"
  NetworkPowerPort:
    model: ubus
    host: "http://192.168.128.2/ubus"
    index: 2
  TFTPProvider:
    internal: "/srv/tftp/tplink_tl-wr842n-v3/"
    external: "tplink_tl-wr842n-v3/"
    external_ip: "192.168.102.1"
  NetworkService:
    address: "192.168.1.1%vlan102"
    username: "root"
