aparcar-turris:
  location: aparcar-desk
  RawSerialPort:
    port: "/dev/ttyUSB0"
  NetworkPowerPort:
    model: shelly_gen3
    host: "http://192.168.27.159"
    index: 0
  TFTPProvider:
    internal: "/srv/tftp/turris/"
    external: "turris/"
  NetworkService:
    address: "cznic_turris-omnia"
    username: "root"

aparcar-openwrt_one:
  location: aparcar-desk
  RawSerialPort:
    port: "/dev/ttyACM0"
  NetworkPowerPort:
    model: ubus
    host: "http://192.168.128.2/ubus"
    index: 3
  TFTPProvider:
    internal: "/srv/tftp/openwrt_one/"
    external: "/openwrt_one/"
  NetworkService:
    address: "openwrt_one"
    username: "root"

aparcar-linksys_e8450:
  location: aparcar-desk
  RawSerialPort:
    port: "/dev/ttyUSB1"
  NetworkPowerPort:
    model: ubus
    host: "http://192.168.128.2/ubus"
    index: 5
  TFTPProvider:
    internal: "/srv/tftp/linksys_e8450/"
    external: "/linksys_e8450/"
  NetworkService:
    address: "linksys_e8450"
    username: "root"
