labgrid-aparcar-openwrt_one:
  location: aparcar-desk
  USBSerialPort:
    match:
      ID_PATH: platform-xhci-hcd.1-usb-0:1.3:1.0
  NetworkPowerPort:
    model: ubus
    host: "http://192.168.128.2/ubus"
    index: 3
  TFTPProvider:
    internal: "/srv/tftp/openwrt_one/"
    external: "openwrt_one/"
  NetworkService:
    address: "192.168.1.1%vlan103"
    username: "root"

labgrid-aparcar-tplink_tl-wdr3600-v1:
  location: aparcar-desk
  USBSerialPort:
    match:
      ID_PATH: platform-xhci-hcd.1-usb-0:1.1.4:1.0
  NetworkPowerPort:
    model: ubus
    host: "http://192.168.128.2/ubus"
    index: 5
  TFTPProvider:
    internal: "/srv/tftp/tplink_tl-wdr3600-v1/"
    external: "tplink_tl-wdr3600-v1/"
    external_ip: "192.168.105.1"
  NetworkService:
    address: "192.168.1.1%vlan105"
    username: "root"

labgrid-aparcar-genexis_pulse-ex400:
  location: aparcar-desk
  USBSerialPort:
    match:
      ID_PATH: platform-xhci-hcd.1-usb-0:1.4:1.0
  PDUDaemonPort:
    host: localhost:16421
    pdu: 192.168.128.2
    index: 1
  TFTPProvider:
    internal: "/srv/tftp/genexis_pulse-ex400/"
    external: "genexis_pulse-ex400/"
  NetworkService:
    address: "192.168.1.1%vlan101"
    username: "root"

labgrid-aparcar-enterasys_ws-ap3710i:
  location: aparcar-desk
  RawSerialPort:
    port: "/dev/serial/by-path/platform-xhci-hcd.1-usb-0:1.1.1:1.0-port0"
  NetworkPowerPort:
    model: ubus
    host: "http://192.168.128.2/ubus"
    index: 7
  TFTPProvider:
    internal: "/srv/tftp/enterasys_ws-ap3710i/"
    external: "enterasys_ws-ap3710i/"
    external_ip: "192.168.106.1"
  NetworkService:
    address: "192.168.1.1%vlan106"
    username: "root"
