labgrid-bastian-cznic_turris-omnia:
  location: bastian-desk
  USBSerialPort:
    match:
      ID_SERIAL_SHORT: AI024GU9
      ID_USB_INTERFACE_NUM: "00"
  PDUDaemonPort:
    host: localhost:16421
    pdu: 192.168.128.2
    index: 1
  TFTPProvider:
    internal: "/srv/tftp/cznic_turris-omnia/"
    external: "cznic_turris-omnia/"
  NetworkService:
    address: "192.168.1.1%vlan101"
    username: "root"

labgrid-bastian-tplink_tl-wdr4300-v1:
  USBSerialPort:
    match:
      ID_SERIAL_SHORT: AI024KC7
      ID_USB_INTERFACE_NUM: "00"
  PDUDaemonPort:
    host: localhost:16421
    pdu: 192.168.128.2
    index: 3
  TFTPProvider:
    internal: "/srv/tftp/tplink_tl-wdr4300-v1/"
    external: "tplink_tl-wdr4300-v1/"
    external_ip: "192.168.103.1"
  NetworkService:
    address: "192.168.1.1%vlan103"
    username: "root"
