labgrid-bastian-cznic_turris-omnia:
  location: bastian-desk
  RawSerialPort:
    port: "/dev/ttyUSB0"
  NetworkPowerPort:
    model: ubus
    host: "http://192.168.128.2/ubus"
    index: 1
  TFTPProvider:
    internal: "/srv/tftp/cznic_turris-omnia/"
    external: "cznic_turris-omnia/"
  NetworkService:
    address: "192.168.1.1%vlan101"
    username: "root"

labgrid-bastian-tplink_tl-wdr4300-v1:
  RawSerialPort:
    port: "/dev/ttyUSB1"
  NetworkPowerPort:
    model: ubus
    host: "http://192.168.128.2/ubus"
    index: 3
  TFTPProvider:
    internal: "/srv/tftp/tplink_tl-wdr4300-v1/"
    external: "tplink_tl-wdr4300-v1/"
  NetworkService:
    address: "192.168.1.1%vlan103"
    username: "root"
