labgrid-aparcar-openwrt_one:
  location: aparcar-desk
  RawSerialPort:
    port: "/dev/serial/by-id/usb-OpenWrt_OpenWrt_One_0000-if00"
  NetworkPowerPort:
    model: ubus
    host: "http://192.168.128.2/ubus"
    index: 3
  TFTPProvider:
    internal: "/srv/tftp/openwrt_one/"
    external: "openwrt_one/"
  NetworkService:
    address: "192.168.1.1%vlan103"
    username: "root"

labgrid-aparcar-tplink_tl-wdr3600-v1:
  location: aparcar-desk
  RawSerialPort:
    port: "/dev/serial/by-id/usb-Prolific_Technology_Inc._USB-Serial_Controller-if00-port0"
  NetworkPowerPort:
    model: ubus
    host: "http://192.168.128.2/ubus"
    index: 5
  TFTPProvider:
    internal: "/srv/tftp/tplink_tl-wdr3600-v1/"
    external: "tplink_tl-wdr3600-v1/"
  NetworkService:
    address: "192.168.1.1%vlan105"
    username: "root"

labgrid-aparcar-genexis_pulse-ex400:
  location: aparcar-desk
  RawSerialPort:
    port: "/dev/serial/by-id/usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_0001-if00-port0"
  NetworkPowerPort:
    model: ubus
    host: "http://192.168.128.2/ubus"
    index: 1
  TFTPProvider:
    internal: "/srv/tftp/genexis_pulse-ex400/"
    external: "genexis_pulse-ex400/"
  NetworkService:
    address: "192.168.1.1%vlan101"
    username: "root"
