network:
  version: 2
  ethernets:
    {{ ethernet_interface }}:
      addresses:
        - 192.168.128.1/24
  vlans:
  {% for vlan in range(0, vlans) %}
    vlan{{ vlan + 101 }}:
      id: {{ vlan + 101 }}
      link: {{ ethernet_interface}}
      addresses:
          - 192.168.{{ vlan + 101 }}.1/24
          - 192.168.1.{{ vlan + 101 }}/24
  {% endfor %}
