network:
  version: 2
  renderer: NetworkManager
  ethernets:
    eth0:
      addresses:
        - 192.168.128.1/24
  wifis:
    wlan0:
      access-points:
        "{{ wifi_ssid }}":
          auth:
            key-management: psk
            password: "{{ wifi_password }}"
      dhcp4: true
  vlans:
{% for vlan in range(0, vlans) %}
    vlan{{ vlan + 101 }}:
      id: {{ vlan + 101 }}
      link: {{ ethernet_interface }}
      addresses:
        - 192.168.{{ vlan + 101 }}.1/24
        - 192.168.1.{{ vlan + 101 }}/24
{% endfor %}
    vlan200:
      id: 200
      link: {{ ethernet_interface}}
      addresses:
          - 192.168.200.1/24
          - 192.168.1.200/24
