
labgrid-bryan-glinet_gl-mt6000:
  location: labgrid-bryan
  USBSerialPort:
    port: "/dev/ttyUSB1"
    speed: 115200
  PDUDaemonPort:
    host: localhost:16421
    pdu: tasmota
    index: 2
  TFTPProvider:
    internal: "/srv/tftp/glinet_gl-mt6000"
    external: "glinet_gl-mt6000"
  NetworkService:
    address: "192.168.1.1%vlan103"
    username: "root"

labgrid-hsn-youku_yk-l1:
  location: labgrid-bryan
  USBSerialPort:
    port: '/dev/ttyUSB2'
  location: labgrid-bryan
  USBSerialPort:
    port: "/dev/ttyUSB0"
    speed: 115200
  PDUDaemonPort:
    host: localhost:16421
    pdu: tasmota
    index: 1
  TFTPProvider:
    internal: "/srv/tftp/youku_yk-l1"
    external: "youku_yk-l1"
  NetworkService:
    address: "192.168.1.1%vlan101"
    username: "root"
