labgrid-bryan-glinet_gl-mt6000:
  location: labgrid-bryan
  USBSerialPort:
    port: "/dev/ttyUSB1"
    speed: 115200
  PDUDaemonPort:
    host: localhost:16421
    pdu: tasmota
    index: 1
  TFTPProvider:
    internal: "/srv/tftp/glinet_gl-mt6000"
    external: "glinet_gl-mt6000"
  NetworkService:
    address: "192.168.1.1%vlan101"
    username: "root"
